using System.Text;
using Collector.ActiveDirectory.Helpers.PolicyRegistry.Xml;
using Polly;
using Polly.Retry;
using Shared.Extensions;
using YAXLib;

namespace Collector.ActiveDirectory.Helpers.PolicyRegistry;

public static class PolicyRegistryHelper
{
    private static readonly ISet<string> BuiltinChannels = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "Application",
        "Security",
        "System"
    };
    
    private static readonly RetryPolicy IoPolicy = Policy.Handle<IOException>().WaitAndRetry(3, sleepDurationProvider: _ => TimeSpan.FromSeconds(1));

    public static void SetGroupPolicyRegistry(string rootPath, ICollection<string> channels)
    {
        var filteredChannels = channels.Where(channel => !BuiltinChannels.Contains(channel)).ToHashSet();
        if (filteredChannels.Count == 0) return;
        var registryPath = $@"{rootPath}\Machine\Preferences\Registry";
        var xmlPath = $@"{registryPath}\Registry.xml";
        IoPolicy.Execute(() => Directory.CreateDirectory(registryPath));
        IoPolicy.Execute(() => File.WriteAllText(xmlPath, Build(filteredChannels)));
    }

    private static string Build(IEnumerable<string> channels)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
        sb.AppendLine(BuildRegistryXml(channels));
        return sb.ToString();
    }

    private static string BuildRegistryXml(IEnumerable<string> channels)
    {
        var settings = new RegistrySettings
        {
            Clsid = "{A3CCFC41-DFDB-43a5-8D26-0FE8B954DA51}",
            Collections = new List<Collection>
            {
                new Collection
                {
                    Clsid = "{53B533F5-224C-47e3-B01B-CA3B3F3FF4BF}",
                    Name = "Registry Wizard Values",
                    Status = "Values generated by the Registry Wizard",
                    Changed = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"),
                    Uid = Shared.Constants.CompanyName.ToGuid().ToString("B"),
                    Collections = new List<Collection>
                    {
                        new Collection
                        {
                            Clsid = "{53B533F5-224C-47e3-B01B-CA3B3F3FF4BF}",
                            Name = "HKEY_LOCAL_MACHINE",
                            Collections = new List<Collection>
                            {
                                new Collection
                                {
                                    Clsid = "{53B533F5-224C-47e3-B01B-CA3B3F3FF4BF}",
                                    Name = "SOFTWARE",
                                    Collections = new List<Collection>
                                    {
                                        new Collection
                                        {
                                            Clsid = "{53B533F5-224C-47e3-B01B-CA3B3F3FF4BF}",
                                            Name = "Microsoft",
                                            Collections = new List<Collection>
                                            {
                                                new Collection
                                                {
                                                    Clsid = "{53B533F5-224C-47e3-B01B-CA3B3F3FF4BF}",
                                                    Name = "Windows",
                                                    Collections = new List<Collection>
                                                    {
                                                        new Collection
                                                        {
                                                            Clsid = "{53B533F5-224C-47e3-B01B-CA3B3F3FF4BF}",
                                                            Name = "CurrentVersion",
                                                            Collections = new List<Collection>
                                                            {
                                                                new Collection
                                                                {
                                                                    Clsid = "{53B533F5-224C-47e3-B01B-CA3B3F3FF4BF}",
                                                                    Name = "WINEVT",
                                                                    Collections = new List<Collection>
                                                                    {
                                                                        new Collection
                                                                        {
                                                                            Clsid = "{53B533F5-224C-47e3-B01B-CA3B3F3FF4BF}",
                                                                            Name = "Channels"
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        };

        var root = GetChannelsCollectionRoot(settings);
        root.Collections ??= new List<Collection>();
        foreach (var channel in channels)
        {
            root.Collections.Add(new Collection
            {
                Clsid = "{53B533F5-224C-47e3-B01B-CA3B3F3FF4BF}",
                Name = channel,
                Registries = new List<Registry>
                {
                    new Registry
                    {
                        Clsid = "{9CD4B2F4-923D-47f5-A062-E897DD1DAD50}",
                        Name = "Enabled",
                        Description = "Wizard Generated Registry Item",
                        Image = "12",
                        Properties = new List<Properties>
                        {
                            new Properties
                            {
                                Action = "U",
                                Hive = "HKEY_LOCAL_MACHINE",
                                Key = $"SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\{channel}",
                                Name = "Enabled",
                                Default = "0",
                                Type = "REG_DWORD",
                                DisplayDecimal = "0",
                                Value = "00000001"
                            }
                        }
                    }
                }
            });
        }

        var serializer = new YAXSerializer(typeof(RegistrySettings));
        return serializer.Serialize(settings);
    }

    private static void TraverseCollections(Collection? root, ref Collection leaf)
    {
        if (root?.Collections is not null && root.Collections.Count == 1)
        {
            leaf = root.Collections[0];
            TraverseCollections(leaf, ref leaf);
        }
    }

    private static Collection GetChannelsCollectionRoot(RegistrySettings settings)
    {
        var leaf = settings.Collections?.SingleOrDefault() ?? new Collection();
        TraverseCollections(leaf, ref leaf);
        return leaf;
    }
}